spring:
  application:
    name: payment-service
  profiles:
    active: dev
  config:
    import: optional:configserver:http://localhost:8888

server:
  port: 8083

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

resilience4j:
  circuitbreaker:
    instances:
      userService:
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 2

# Debug logging for resilience4j
logging:
  level:
    io.github.resilience4j: DEBUG
    io.github.resilience4j.circuitbreaker: DEBUG
    com.microservices.PaymentServices.client: DEBUG